#Photo Booth Config:
"CAMERA_BUTTON_PIN" : 26 # GPIO pin that is connected to 'take photo' button
"EXIT_BUTTON_PIN"   : 13 # GPIO pin that is connected to 'exit' button (optional)
"FLASH_PIN"         : 16 # GPIO pin that is connected to the light relay
"TOTAL_PICS"        : 4  # Number of pics to be taken
"PREP_DELAY"        : 3  # Number of seconds as users prepare to have photo taken, before countdown commences
"COUNTDOWN"         : 5  # Number of seconds to count down from

#GPIO Debounce Duration
# (This may help avoid "phantom presses" caused by electronic interference)
"DEBOUNCE_TIME"     : 0.1 # Min duration (seconds) button is required to be "pressed in" for.

# Take photos at this resolution:
"PHOTO_W"           : 3280
"PHOTO_H"           : 2464
#Note:
# - The max resolution for PiCamera v2, is: 3280x2464 , assuming you are running the latest firmware.
# - To upgrade your firmware, please run:
#   sudo apt-get dist-upgrade

# Resolution of the photo booth display:
"SCREEN_W"          : 1024
"SCREEN_H"          : 768

# Camera setup
"CAMERA_ROTATION"   : 0 # Rotation of the camera
"CAMERA_HFLIP"      : True # When preparing for photos, the preview will be flipped horizontally.

#Flash mode
"FLASH_MODE"        : FALSE

# Printer service
"PRINTER_MODE"      : FALSE # Service which merge 4 photos on a specific design and send to printer

# Primary folder to save images to (required):
"SAVE_RAW_IMAGES_FOLDER" : "photos"

# Additional locations where images will be saved to (optional):
"COPY_IMAGES_TO" : "/Photobox"

# Test purposes only:
"TESTMODE_AUTOPRESS_BUTTON" : FALSE # Should the button be automatically pressed? (only used for testing)
"TESTMODE_FAST"             : FALSE # Reduced wait between photos and 2 photos only
